# Generated by Django 3.0.2 on 2020-01-08 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='persondata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.PersonType'),
        ),
    ]
