# Generated by Django 3.0.2 on 2020-01-05 19:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'teacher'), (1, 'student'), (2, 'external')])),
                ('id_card_number', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('ucab_email', models.EmailField(max_length=254, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('secondary_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('observations', models.CharField(max_length=1024)),
            ],
        ),
    ]
