# Generated by Django 3.0.2 on 2020-01-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_persondata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persondata',
            options={'verbose_name_plural': 'Person data'},
        ),
        migrations.AlterField(
            model_name='persondata',
            name='observations',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Teacher'), (1, 'Student'), (2, 'External')]),
        ),
    ]
