# Generated by Django 3.0.2 on 2020-01-08 02:11

from django.db import migrations


# noinspection PyPep8Naming
def populate_proposal_statuses(apps, schema_editor):
    ProposalStatus = apps.get_model('web', 'ProposalStatus')
    ProposalStatus(name='Por evaluar').save()
    ProposalStatus(name='Diferida').save()
    ProposalStatus(name='Aprobada').save()
    ProposalStatus(name='Rechazada').save()


# noinspection PyPep8Naming
def populate_thesis_statuses(apps, schema_editor):
    ThesisStatus = apps.get_model('web', 'ThesisStatus')
    ThesisStatus(name='Por entregar').save()
    ThesisStatus(name='Entregado y pendiente por defender').save()
    ThesisStatus(name='Diferido').save()
    ThesisStatus(name='Aprobado').save()
    ThesisStatus(name='Rechazado').save()
    ThesisStatus(name='Aprobado con solicitud de correcciones').save()


# noinspection PyPep8Naming
def populate_person_types(apps, schema_editor):
    PersonType = apps.get_model('web', 'PersonType')
    PersonType(name='Profesor').save()
    PersonType(name='Estudiante').save()
    PersonType(name='Externo').save()


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0002_auto_20200107_2210'),
    ]

    operations = [
        migrations.RunPython(populate_proposal_statuses),
        migrations.RunPython(populate_thesis_statuses),
        migrations.RunPython(populate_person_types),
    ]
