# Generated by Django 3.0.2 on 2020-01-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_default_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defence',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defence',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
