# Generated by Django 3.0.2 on 2020-01-05 20:15

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0003_auto_20200105_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='observations',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='ucab_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('submission_date', models.DateField()),
                ('title', models.CharField(max_length=256)),
                ('term', models.CharField(max_length=6)),
                ('academic_tutor',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_tutor',
                                   to='web.PersonData')),
                ('industry_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                                     related_name='industry_tutor', to='web.PersonData')),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student1',
                                               to='web.PersonData')),
                ('student2',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student2',
                                   to='web.PersonData')),
            ],
        ),
    ]
