# Generated by Django 3.0.2 on 2020-01-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0004_auto_20200105_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='id',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='code',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HistoricProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Proposal')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ProposalStatus')),
            ],
        ),
        migrations.AlterField(
            model_name='proposal',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term', to='web.Term'),
        ),
    ]
