# Generated by Django 3.0.2 on 2020-01-05 22:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0005_auto_20200105_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defence',
            fields=[
                ('code', models.CharField(max_length=68, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('grade', models.PositiveSmallIntegerField()),
                ('is_publication_mention', models.BooleanField()),
                ('is_honorific_mention', models.BooleanField()),
                ('corrections_submission_date', models.DateField(blank=True, null=True)),
                ('was_grade_loaded', models.BooleanField()),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ThesisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'verbose_name_plural': 'Thesis statuses',
            },
        ),
        migrations.AlterModelOptions(
            name='proposalstatus',
            options={'verbose_name_plural': 'Proposal statuses'},
        ),
        migrations.AlterField(
            model_name='persondata',
            name='observations',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='ucab_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='industry_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='industry_tutor', to='web.PersonData'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='student2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='student2', to='web.PersonData'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='proposalstatus',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('code', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('NRC', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=50)),
                ('thematic_category', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('company_name', models.CharField(blank=True, max_length=128, null=True)),
                ('delivery_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Term')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_assistance', models.BooleanField(default=False)),
                ('is_backup_jury', models.BooleanField(default=False)),
                ('defence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Defence')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.PersonData')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricThesisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ThesisStatus')),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Thesis')),
            ],
        ),
        migrations.AddField(
            model_name='defence',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Thesis'),
        ),
    ]
