# Generated by Django 3.0.2 on 2020-01-09 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0002_default_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='status',
        ),
    ]
