# Generated by Django 3.0.2 on 2020-01-09 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0004_auto_20200108_1153'),
        ('web', '0005_auto_20200108_2301'),
    ]

    operations = [
    ]
