# Generated by Django 3.0.2 on 2020-01-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0007_test_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defence',
            name='is_honorific_mention',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defence',
            name='is_publication_mention',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defence',
            name='was_grade_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
