# Generated by Django 3.0.2 on 2020-01-06 13:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0007_populate_default_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicproposalstatus',
            options={'verbose_name_plural': 'Historic proposal statuses'},
        ),
        migrations.AlterModelOptions(
            name='historicthesisstatus',
            options={'verbose_name_plural': 'Historic thesis statuses'},
        ),
        migrations.AlterModelOptions(
            name='thesis',
            options={'verbose_name_plural': 'Thesis'},
        ),
    ]
