# Generated by Django 3.0.2 on 2020-01-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200110_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicthesisstatus',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
