# Generated by Django 3.0.2 on 2020-01-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200110_0259'),
        ('web', '0009_auto_20200110_0345'),
    ]

    operations = [
    ]
